joint_limits:
  joint_l:
    has_velocity_limits: true
    max_velocity: 3.4906586
    has_acceleration_limits: false
    max_acceleration: 0
  joint_r:
    has_velocity_limits: true
    max_velocity: 3.4906586
    has_acceleration_limits: false
    max_acceleration: 0
  joint_b:
    has_velocity_limits: true
    max_velocity: 4.01425739
    has_acceleration_limits: false
    max_acceleration: 0
  joint_s:
    has_velocity_limits: true
    max_velocity: 3.4906586
    has_acceleration_limits: false
    max_acceleration: 0
  joint_t:
    has_velocity_limits: true
    max_velocity: 6.10865255
    has_acceleration_limits: false
    max_acceleration: 0
  joint_e:
    has_velocity_limits: true
    max_velocity: 3.4906586
    has_acceleration_limits: false
    max_acceleration: 0
  joint_u:
    has_velocity_limits: true
    max_velocity: 3.4906586
    has_acceleration_limits: false
    max_acceleration: 0